apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: db-cluster
spec:
  replicas: 2
  secretName: db-secret

  ## Specify additional pod specification
  podSpec:
    resources:
      requests:
        memory: 256Mi
        cpu:    100m

  ## Specify additional volume specification
  volumeSpec:
    accessModes: [ "ReadWriteOnce" ]
    storageClassName: rook-ceph-block
    resources:
      requests:
        storage: 1Gi
