apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-app-nfs-pv-claim
spec:
  storageClassName: rook-nfs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
