variables:
  k8s_coreos_stable_box_url: https://storage.googleapis.com/stable.release.core-os.net/amd64-usr/current/coreos_production_vagrant.json
  k8s_coreos_alpha_box_url: https://storage.googleapis.com/alpha.release.core-os.net/amd64-usr/current/coreos_production_vagrant.json
  k8s_coreos_beta_box_url: https://storage.googleapis.com/beta.release.core-os.net/amd64-usr/current/coreos_production_vagrant.json

# k8s config backport from kubespray https://github.com/kubernetes-incubator/kubespray/blob/master/Vagrantfile#L26
teracy-dev-k8s:
  # configurable here
  kubespray:
    lookup_path: extensions # relative to the Vagrantfile
    location:
      git:
        remote:
          origin: https://github.com/kubernetes-sigs/kubespray.git
        branch: v2.8.1
  ansible:
    verbose: v
    mode: guest # or host to run ansible from the host instead of from the guest
    playbook_path: cluster.yml # relative within the kubespray repo or /cluster.yml is relative to the Vagrantfile when appending / at the beginning as convention
    # you can add any host_vars here with key-value to override inventory
    version: # ansible guest version
    host_vars:
      kube_network_plugin: flannel
      kube_network_plugin_multus: "False"
      docker_keepcache: "1"
      download_localhost: "False"
      download_run_once: "False"
      kubeconfig_localhost: "True"
      kubectl_localhost: "True"

  num_instances: 1
  instance_name_prefix: "k8s"
  vm_gui: false
  vm_memory: 2048
  vm_cpus: 2
  os: ubuntu # must match one of the _id from supported_oses
  supported_oses:
    # ubuntu
    - _id: ubuntu
      box: bento/ubuntu-18.04
      user: vagrant
    # coreos
    - _id: coreos-stable
      box: coreos-stable
      user: core
      box_url: "%{k8s_coreos_stable_box_url}"
    - _id: coreos-alpha
      box: coreos-alpha
      user: core
      box_url: "%{k8s_coreos_alpha_box_url}"
    - _id: coreos-beta
      box: coreos-beta
      user: core
      box_url: "%{k8s_coreos_beta_box_url}"
    # centos
    - _id: centos
      box: centos/7
      user: vagrant
    # opensuse
    - _id: opensuse
      box: opensuse/openSUSE-42.3-x86_64
      user: vagrant
    - _id: opensuse-tumbleweed
      box: opensuse/openSUSE-Tumbleweed-x86_64
      user: vagrant
    # fedora
    - _id: fedora
      box: fedora/28-cloud-base
      user: vagrant

  network:
    type: "private_network" # TODO: support "public_network" with automatic public ip of the master node so it's LAN accessible
    subnet: 172.17.8

  # don't try to change node_template if you don't know what you're going to do
  # node template to be overriden
  node_template:
    _id:
    name:
    vm:
      box:
      box_version:
      box_url:
      networks:
        - _id: "0"
          type:
          ip:
    ssh:
      insert_key: false
      username:
    providers:
      - _id: "0"
        gui:
        memory:
        cpus:
        description: "k8s #{Time.now.getutc.to_i}"
    provisioners:
      - _id: "k8s-0"
        name: "teracy-dev-k8s-swapoff"
        type: shell
        enabled: true
        inline: swapoff -a
