# k8s config backport from kubespray https://github.com/kubernetes-incubator/kubespray/blob/master/Vagrantfile#L26
teracy-dev-k8s:
  # configurable here
  kubespray:
    lookup_path: extensions # relative to the Vagrantfile
    location:
      git: https://github.com/kubernetes-incubator/kubespray.git
      branch: v2.6.0
  ansible:
    verbose: v
    mode: guest # or host to run ansible from the host instead of from the guest
    playbook_path: cluster.yml # relative within the kubespray repo or /cluster.yml is relative to the Vagrantfile when appending / at the beginning as convention
    # you can add any host_vars here with key-value to override inventory
    host_vars:
      local_release_dir: /tmp/release/
      kube_network_plugin: flannel
      download_run_once: "False"
      kubeconfig_localhost: "True"
      kubectl_localhost: "True"

  num_instances: 1
  instance_name_prefix: "k8s"
  vm_gui: false
  vm_memory: 2048
  vm_cpus: 1
  os: ubuntu # coreos-stable | coreos-alpha | coreos-beta | centos | opensuse | opensuse-tumbleweed
  network:
    type: "private_network" # TODO: support "public_network" with automatic public ip of the master node so it's LAN accessible
    subnet: 172.17.8

  # don't try to change node_template if you don't know what you're going to do
  # node template to be overriden
  node_template:
    _id:
    name:
    vm:
      box:
      box_version:
      box_url:
      networks:
        - _id: "0"
          type:
          ip:
    ssh:
      insert_key: false
      username:
    providers:
      - _id: "0"
        gui:
        memory:
        cpus:
        description: "k8s #{Time.now.getutc.to_i}"
    provisioners:
      - _id: "k8s-0"
        name: "swapoff"
        type: shell
        enabled: true
        inline: swapoff -a
