apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: accounts-k8s-local
spec:
  secretName: accounts-k8s-local-tls
  issuerRef:
    name: ca-cluster-issuer
    kind: ClusterIssuer
  commonName: accounts.k8s.local
  organization:
  - Dex
  dnsNames:
  - accounts.k8s.local
